// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://midas.dev/terms",
        "contact": {
            "name": "API Support",
            "url": "https://midas.dev/support",
            "email": "support@midas.dev"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/fair-value/bulk": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Calculate intrinsic fair values for multiple stocks in a single request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fair-value"
                ],
                "summary": "Get fair values for multiple stocks",
                "parameters": [
                    {
                        "description": "Bulk fair value request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers.BulkFairValueRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers.BulkFairValueResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request format",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API key",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Insufficient permissions",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Rate limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/fair-value/{ticker}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Calculate intrinsic fair value for a stock using DCF and net tangible assets",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fair-value"
                ],
                "summary": "Get fair value for a stock",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stock ticker symbol (e.g., AAPL)",
                        "name": "ticker",
                        "in": "path",
                        "required": true
                    },
                    {
                        "maximum": 5,
                        "minimum": -5,
                        "type": "number",
                        "description": "Override beta for WACC calculation",
                        "name": "override_beta",
                        "in": "query"
                    },
                    {
                        "maximum": 0.25,
                        "minimum": -0.05,
                        "type": "number",
                        "description": "Override risk-free rate",
                        "name": "override_rf",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers.FairValueResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid ticker or parameters",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API key",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Insufficient permissions",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Ticker not found",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Rate limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Calculate intrinsic fair value for a stock; optional JSON body accepts per-request valuation knob overrides",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fair-value"
                ],
                "summary": "Post fair value for a stock with optional overrides",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stock ticker symbol (e.g., AAPL)",
                        "name": "ticker",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Optional override options",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers.SingleFairValueRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers.FairValueResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid ticker or parameters",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API key",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Insufficient permissions",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Ticker not found",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Invalid override knob value",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Rate limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_midas_dcf-valuation-api_internal_core_entities.SanityCheck": {
            "type": "object",
            "properties": {
                "flags": {
                    "description": "Specific warnings about divergences",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "implied_ev_ebitda": {
                    "description": "DCF enterprise value / EBITDA",
                    "type": "number"
                },
                "implied_pe": {
                    "description": "DCF value / EPS",
                    "type": "number"
                },
                "implied_pfcf": {
                    "description": "DCF value per share / FCF per share (omitted when zero FCF)",
                    "type": "number"
                },
                "is_reasonable": {
                    "description": "True if implied multiples are within 0.5x-2x of sector medians",
                    "type": "boolean"
                },
                "sector_median_ev_ebitda": {
                    "description": "Sector median EV/EBITDA",
                    "type": "number"
                },
                "sector_median_pe": {
                    "description": "Sector median P/E ratio",
                    "type": "number"
                },
                "sector_median_pfcf": {
                    "description": "Sector median P/FCF ratio (omitted when unknown)",
                    "type": "number"
                }
            }
        },
        "github_com_midas_dcf-valuation-api_internal_services_valuation_profile.ResolutionTrace": {
            "type": "object",
            "properties": {
                "config_hash": {
                    "type": "string"
                },
                "config_version": {
                    "type": "string"
                },
                "fallback_reason": {
                    "type": "string"
                },
                "human_reason": {
                    "type": "string"
                },
                "matched_rule_id": {
                    "type": "string"
                },
                "missing_facts": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "profile_id": {
                    "type": "string"
                },
                "resolver_version": {
                    "type": "string"
                },
                "source": {
                    "$ref": "#/definitions/github_com_midas_dcf-valuation-api_internal_services_valuation_profile.Source"
                }
            }
        },
        "github_com_midas_dcf-valuation-api_internal_services_valuation_profile.Source": {
            "type": "string",
            "enum": [
                "explicit",
                "inferred",
                "fallback"
            ],
            "x-enum-varnames": [
                "SourceExplicit",
                "SourceInferred",
                "SourceFallback"
            ]
        },
        "internal_api_v1_handlers.AppliedOverride": {
            "description": "Per-knob override echo in the applied_overrides response field",
            "type": "object",
            "properties": {
                "source": {
                    "description": "Source is the precedence layer that supplied this value. Always \"request\" in v1.",
                    "type": "string"
                },
                "value": {
                    "description": "Value is the resolved scalar that the engine used. Type matches the knob:\nfloat64 for rate/multiplier fields, int for year fields, string for method fields."
                }
            }
        },
        "internal_api_v1_handlers.BulkFailure": {
            "type": "object",
            "properties": {
                "error_code": {
                    "type": "string"
                },
                "knob": {
                    "description": "Knob is the name of the override parameter that caused an INVALID_OVERRIDE\nerror. Empty (and omitted) for non-override error codes. Mirrors the\ncontext.knob field in the single-ticker 422 ErrorResponse.",
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "ticker": {
                    "type": "string"
                }
            }
        },
        "internal_api_v1_handlers.BulkFairValueRequest": {
            "description": "Bulk fair value calculation request for multiple tickers",
            "type": "object",
            "required": [
                "tickers"
            ],
            "properties": {
                "options": {
                    "description": "Options carries structured per-request valuation knob overrides applied to\nALL tickers in the batch. When set, it must not duplicate any knob that is\nalso set via the legacy OverrideBeta / OverrideRiskFree fields — the\nrequest is rejected 422 with code \"INVALID_OVERRIDE\" if both are present\nfor the same knob.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/internal_api_v1_handlers.ValuationOverrides"
                        }
                    ]
                },
                "override_beta": {
                    "description": "Optional beta override (legacy; prefer options.beta)",
                    "type": "number",
                    "example": 1.2
                },
                "override_rf": {
                    "description": "Optional risk-free rate override (legacy; prefer options.risk_free_rate)",
                    "type": "number",
                    "example": 0.045
                },
                "tickers": {
                    "description": "Stock ticker symbols (max 10)",
                    "type": "array",
                    "maxItems": 10,
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[\"AAPL\"",
                        "\"MSFT\"",
                        "\"GOOGL\"]"
                    ]
                }
            }
        },
        "internal_api_v1_handlers.BulkFairValueResponse": {
            "type": "object",
            "properties": {
                "failures": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_api_v1_handlers.BulkFailure"
                    }
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_api_v1_handlers.FairValueResponse"
                    }
                },
                "summary": {
                    "$ref": "#/definitions/internal_api_v1_handlers.BulkSummary"
                }
            }
        },
        "internal_api_v1_handlers.BulkSummary": {
            "type": "object",
            "properties": {
                "failed": {
                    "type": "integer"
                },
                "successful": {
                    "type": "integer"
                },
                "total_requested": {
                    "type": "integer"
                }
            }
        },
        "internal_api_v1_handlers.ErrorResponse": {
            "description": "Standard error response following RFC 7807 Problem Details",
            "type": "object",
            "properties": {
                "code": {
                    "description": "Error code (RFC 7807 extension)",
                    "type": "string",
                    "example": "INVALID_TICKER"
                },
                "context": {
                    "description": "Additional context information",
                    "type": "object",
                    "additionalProperties": true
                },
                "detail": {
                    "description": "Human-readable explanation",
                    "type": "string",
                    "example": "Invalid ticker format"
                },
                "instance": {
                    "description": "URI reference to specific occurrence",
                    "type": "string",
                    "example": "/api/v1/fair-value/INVALID"
                },
                "method": {
                    "description": "HTTP method (RFC 7807 extension)",
                    "type": "string",
                    "example": "GET"
                },
                "status": {
                    "description": "HTTP status code",
                    "type": "integer",
                    "example": 400
                },
                "timestamp": {
                    "description": "ISO 8601 timestamp (RFC 7807 extension)",
                    "type": "string"
                },
                "title": {
                    "description": "Human-readable title",
                    "type": "string",
                    "example": "Bad Request"
                },
                "type": {
                    "description": "Problem type URI",
                    "type": "string",
                    "example": "https://problems.midas.dev/INVALID_TICKER"
                }
            }
        },
        "internal_api_v1_handlers.FairValueResponse": {
            "description": "Fair value calculation response with intrinsic valuation metrics",
            "type": "object",
            "properties": {
                "adr_ratio_applied": {
                    "description": "ADRRatioApplied is the ordinary-shares-per-ADR multiplier that the\nvaluation engine divided SEC-reported share counts by before\ncomputing per-share values, so the resulting fair value compares\nlike-for-like with the listed ADR price. 1 for domestic 10-K filers\n(and any ticker absent from config/adr_ratios.json); non-1 for\nconfigured ADRs (TSM=5, BABA=8, …). Phase B10 of the IFRS-FPI plan.\nOmitted from the JSON when zero (defensive — the service always\nstamps a positive int via ADRRatios.Get, but omitempty keeps the\nresponse clean if a future bug produces 0).",
                    "type": "integer",
                    "example": 5
                },
                "applied_overrides": {
                    "description": "AppliedOverrides echoes the valuation knobs that were explicitly set by\nthe request, each with the resolved value and source \"request\". Absent\n(omitempty) when no overrides were supplied — default GET responses and\nPOST{} requests are byte-identical (TestPostFairValue_EmptyBody_EqualsGET\npins this). Only request-sourced knobs are echoed in v1 (design §8 R5).\n\nEach entry:\n  \"knob_name\": { \"value\": \u003cresolved scalar\u003e, \"source\": \"request\" }\n\nExample with two overrides:\n  \"applied_overrides\": {\n    \"tax_rate\":    { \"value\": 0.21,  \"source\": \"request\" },\n    \"horizon_years\": { \"value\": 7,   \"source\": \"request\" }\n  }",
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/internal_api_v1_handlers.AppliedOverride"
                    }
                },
                "as_of": {
                    "description": "Timestamp of calculation",
                    "type": "string",
                    "example": "2025-08-13T22:15:34.402652598Z"
                },
                "assumption_profile": {
                    "description": "Tier 2 P0b additive fields. All omitempty — legacy mature-large-bank\nDDM responses remain byte-identical (TestDDM_LegacyPath_BitForBit\npins this). AssumptionProfile is the resolved profile_id so API\nconsumers can correlate the result with the calibration record.\nResolutionTrace carries the full audit trail (matched_rule_id,\nfallback_reason, config_hash) for replay determinism and audit. The\nDCF diagnostic fields are declared here for schema ownership in P0b\neven though P2 fills them — keeps the wire shape stable from this\ncommit forward.",
                    "type": "string",
                    "example": "mature_large_bank:mature"
                },
                "calculation_method": {
                    "description": "Model used: multi_stage_dcf, ddm, ffo, revenue_multiple",
                    "type": "string",
                    "example": "multi_stage_dcf"
                },
                "calculation_version": {
                    "description": "Engine version that produced this result",
                    "type": "string",
                    "example": "4.2"
                },
                "currency": {
                    "description": "Currency is the ISO-4217 code that dcf_value_per_share and\ntangible_value_per_share are denominated in. Always \"USD\" — the\nvaluation service FX-converts each period's reporting-currency\nmonetary fields to USD via Phase B9 of the IFRS-FPI plan\n(docs/refactoring/archive/ifrs-foreign-private-issuer-support-spec.md), so\nAPI consumers MUST NOT re-convert. Surfaced so a downstream client\ncan display \"USD\" alongside the per-share value rather than guessing.",
                    "type": "string",
                    "example": "USD"
                },
                "current_assets_per_share": {
                    "description": "Graham-school asset-floor diagnostics — see\ndocs/refactoring/archive/graham-floor-metrics-spec.md. All four use *float64 +\nomitempty: nil = TotalLiabilities unresolved (a warning is appended to\n` + "`" + `warnings` + "`" + `). Non-nil = resolved; values may be negative (NCAV on\ndistressed companies) or 0 (floor clamped when NCAV is negative). Pointer\ntypes preserve the deep-distress signal (resolved + negative + clamped)\ndistinct from the unresolved-fallback signal (all four absent + warning).",
                    "type": "number",
                    "example": 55.13
                },
                "current_price": {
                    "description": "CurrentPrice is the live per-share market price captured from the\nmarket-data gateway (Yahoo Finance / Finzive) at the moment the\nvaluation was computed. Same denomination and per-share basis as\nDCFValuePerShare and TangibleValuePerShare — for ADRs this is the\nper-ADR exchange price, directly comparable to the per-ADR DCF\nvalue the engine produces after applyADRRatio. Surfaced so a\nconsumer can compute the upside/downside discount ((dcf - price)\n/ price) without a second quote lookup. Omitted when zero.",
                    "type": "number",
                    "example": 190.25
                },
                "data_quality_grade": {
                    "description": "Data quality grade (A-F)",
                    "type": "string",
                    "example": "B"
                },
                "data_quality_score": {
                    "description": "Data quality score (0-100)",
                    "type": "number",
                    "example": 85.5
                },
                "dcf_horizon_years": {
                    "type": "integer",
                    "example": 5
                },
                "dcf_per_year_pv": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "dcf_terminal_growth_used": {
                    "type": "number"
                },
                "dcf_terminal_method": {
                    "type": "string",
                    "example": "gordon_growth"
                },
                "dcf_terminal_pct_of_ev": {
                    "type": "number"
                },
                "dcf_value_per_share": {
                    "description": "Discounted cash flow fair value per share",
                    "type": "number",
                    "example": 156.42
                },
                "graham_discount_pct": {
                    "type": "number",
                    "example": 23.3
                },
                "graham_floor_per_share": {
                    "type": "number",
                    "example": 3.03
                },
                "growth_confidence": {
                    "description": "Growth estimation confidence",
                    "type": "string",
                    "example": "high"
                },
                "growth_rate": {
                    "description": "Summary growth rate (CAGR of projected rates)",
                    "type": "number",
                    "example": 0.045
                },
                "growth_rates": {
                    "description": "Per-year projected growth rates",
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "growth_source": {
                    "description": "Growth estimation source",
                    "type": "string",
                    "example": "analyst_blend"
                },
                "industry": {
                    "description": "Dual industry classification (SIC + heuristic) for drift detection",
                    "allOf": [
                        {
                            "$ref": "#/definitions/internal_api_v1_handlers.Industry"
                        }
                    ]
                },
                "ncav_per_share": {
                    "type": "number",
                    "example": 4.55
                },
                "resolution_trace": {
                    "$ref": "#/definitions/github_com_midas_dcf-valuation-api_internal_services_valuation_profile.ResolutionTrace"
                },
                "sanity_check": {
                    "description": "Multiples cross-check against sector medians",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_midas_dcf-valuation-api_internal_core_entities.SanityCheck"
                        }
                    ]
                },
                "tangible_value_per_share": {
                    "description": "Net tangible book value per share",
                    "type": "number",
                    "example": 24.73
                },
                "ticker": {
                    "description": "Stock ticker symbol",
                    "type": "string",
                    "example": "AAPL"
                },
                "wacc": {
                    "description": "Weighted Average Cost of Capital",
                    "type": "number",
                    "example": 0.092
                },
                "warnings": {
                    "description": "Data quality or assumption warnings",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "internal_api_v1_handlers.GrowthStages": {
            "description": "Three-stage growth estimator duration overrides",
            "type": "object",
            "properties": {
                "stage1_years": {
                    "type": "integer",
                    "example": 3
                },
                "stage2_years": {
                    "type": "integer",
                    "example": 4
                },
                "stage3_years": {
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "internal_api_v1_handlers.Industry": {
            "description": "Dual industry classification (SIC + heuristic) with a Match flag",
            "type": "object",
            "properties": {
                "heuristic_code": {
                    "description": "GICS sector code from IndustryClassifier.ClassifyIndustry",
                    "type": "string",
                    "example": "45"
                },
                "heuristic_name": {
                    "description": "GICS sector name",
                    "type": "string",
                    "example": "Information Technology"
                },
                "match": {
                    "description": "true when SIC and heuristic agree per the canonical mapping",
                    "type": "boolean",
                    "example": true
                },
                "sic": {
                    "description": "SIC-derived industry label from IndustryClassifier.Classify",
                    "type": "string",
                    "example": "MFG"
                },
                "sic_code": {
                    "description": "Raw SIC code from SEC (may be empty if SEC data lacked it)",
                    "type": "string",
                    "example": "3674"
                }
            }
        },
        "internal_api_v1_handlers.SingleFairValueRequest": {
            "description": "POST body for single-ticker fair-value calculation with optional overrides",
            "type": "object",
            "properties": {
                "options": {
                    "description": "Options carries per-request valuation knob overrides. Nil or absent means\n\"use engine defaults\" — identical to calling the GET endpoint.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/internal_api_v1_handlers.ValuationOverrides"
                        }
                    ]
                }
            }
        },
        "internal_api_v1_handlers.ValuationOverrides": {
            "description": "Per-request valuation knob overrides (all fields optional)",
            "type": "object",
            "properties": {
                "beta": {
                    "description": "Beta is the equity beta used in the CAPM cost-of-equity calculation.\nNegative values are allowed (inverse-correlated assets).\nConflicts with the legacy override_beta field on the bulk request.",
                    "type": "number",
                    "example": 1.2
                },
                "growth_stages": {
                    "description": "GrowthStages overrides the three-stage growth estimator configuration.\nWhen any sub-field is set a per-request estimator is built instead of\nreusing the shared service-level estimator.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/internal_api_v1_handlers.GrowthStages"
                        }
                    ]
                },
                "horizon_years": {
                    "description": "DCF forecast horizon in years. When omitted the engine uses the length of\nthe growth-rate slice produced by the estimator (legacy signal).",
                    "type": "integer",
                    "example": 5
                },
                "market_risk_premium": {
                    "description": "MarketRiskPremium is the equity risk premium (ERP) added to the risk-free\nrate in CAPM. Must be ≥ 0; a negative ERP is economically unsound and\nwill be caught by Layer-1 validation (T7).",
                    "type": "number",
                    "example": 0.05
                },
                "max_growth_rate": {
                    "description": "MaxGrowthRate is the upper clamp applied inside the growth estimator.\nDefaults to 0.5 (50%). Negative values are meaningless here but accepted.",
                    "type": "number",
                    "example": 0.5
                },
                "min_growth_rate": {
                    "description": "MinGrowthRate is the lower clamp applied inside the growth estimator.\nDefaults to -0.3 (-30%). Negative values represent contraction scenarios.",
                    "type": "number",
                    "example": -0.3
                },
                "risk_free_rate": {
                    "description": "RiskFreeRate is the nominal risk-free rate (e.g. 10-year Treasury yield).\nNegative values are allowed (EUR/JPY/CHF regimes).\nConflicts with the legacy override_rf field on the bulk request and the\noverride_rf query parameter on the GET single-ticker endpoint.",
                    "type": "number",
                    "example": 0.045
                },
                "tax_rate": {
                    "description": "TaxRate is the effective corporate tax rate applied to FCF, WACC, and the\nalt-model ModelInput. Negative values are allowed (NOLs / tax credits).",
                    "type": "number",
                    "example": 0.21
                },
                "terminal_growth_cap": {
                    "description": "Cap applied during auto-derivation of the terminal growth rate.\nDefaults to 0.03 (3%). Has no effect when terminal_growth_rate is set explicitly.",
                    "type": "number",
                    "example": 0.03
                },
                "terminal_growth_rate": {
                    "description": "Terminal growth rate — explicit absolute value for g in Gordon Growth Model.\nNegative values are allowed (real-terms decline). If omitted the engine\nauto-derives g from historical CAGR, capped by terminal_growth_cap.",
                    "type": "number",
                    "example": -0.01
                },
                "terminal_method": {
                    "description": "TerminalMethod selects the terminal-value calculation model.\nAllowed values: \"gordon_growth\" (default) | \"exit_multiple\".\n  - \"gordon_growth\" SUPPRESSES exit-multiple blending: the terminal value is a\n    pure Gordon Growth perpetuity (no exit multiple is mixed in).\n  - \"exit_multiple\" BLENDS an exit-multiple terminal value 50/50 with the Gordon\n    Growth terminal value (the engine AVERAGES the two estimates to reduce\n    single-model dependence; it is NOT a pure exit-multiple terminal value).\n    It requires that a multiple is resolvable (via terminal_multiple or the\n    industry default); if neither is available the request is rejected 422.",
                    "type": "string",
                    "example": "exit_multiple"
                },
                "terminal_multiple": {
                    "description": "TerminalMultiple is the EV/EBITDA (or analogous) exit multiple used when\nterminal_method is \"exit_multiple\". When omitted the engine falls back to\nthe industry default looked up at resolution time.",
                    "type": "number",
                    "example": 14
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "API key required for authentication. Include this in the X-API-Key header.",
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        }
    },
    "externalDocs": {
        "description": "OpenAPI Specification",
        "url": "/docs/openapi.yaml"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "DCF Valuation API",
	Description:      "DCF (Discounted Cash Flow) Valuation API provides intrinsic value calculations for publicly traded companies.\nThe API computes Net Tangible Asset Value and DCF Fair Value per share using SEC filings and market data.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
